### ISSUE TITLE
ModuleNotFoundError: No module named 'pysot.models.predictor.mv_v16_add'

### ISSUE THREAD

**Issue by ParaImage** [Jaraxxus-Me/PVT_pp#3]
`ModuleNotFoundError: No module named 'pysot.models.predictor.mv_v16_add'`

**Comment by Jaraxxus-Me** [comment]
This was caused by some residual code for ablation studies.
I just updated and fixed the bug, should be good now.

**Comment by ParaImage** [comment]
Thanks.
